# generating

- 베이즈에서 랜덤분포를 생성하는것도 굉장히 중요합니다.
- numpy 와 scipy 두가지가 있습니다만, 저는 scipy 를 선호합니다.

https://numpy.org/doc/1.16/reference/routines.random.html#module-numpy.random 를 보도록 하세요~

In [12]:
import scipy
import scipy.stats

## Binomial

In [24]:
sample = scipy.stats.bernoulli.rvs(p = 0.1,
                                   size=100,
                                   random_state = 300)
sample

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0,
       1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

## Beta

- 아래의 경우는 베타분포의 경우에 Sample 을 Generating 하는것입니다. 

In [26]:
sample = scipy.stats.beta.rvs(a=2
                             ,b=3
                             ,size = 10)
sample

array([0.86816302, 0.13358473, 0.42227041, 0.71356493, 0.24522379,
       0.09935627, 0.68399286, 0.55722335, 0.53276295, 0.40302006])

In [6]:
np.random.beta(a=2,b=3,size=10)

array([0.22569631, 0.14994025, 0.39785175, 0.27306364, 0.23922844,
       0.53326515, 0.50218443, 0.21432713, 0.19613248, 0.58364038])